<?php 

/**
 * Plugin Name: Bangla Converter (Bijoy To Unicode, Unicode To Bijoy)
 * Description: This converter will help you to convert your bangla bijoy Ascii text to convert Unicode text or Unicode text to convert bijoy Ascii text. 
 * Plugin URI: https://rumi.pro/bangla-converter
 * Author: SynthiaSoft
 * Author URI: https://synthasoft.com/
 * Version: 1.1.0
 * License: GPL2 or later
 * License URI: https://www.gnu.org/licenses/gpl-2.0.html
 * Text Domain: bangla-converter
 */

// include Library
require_once 'lib/init-libray.php';


add_filter( 'generate_rewrite_rules', function ( $wp_rewrite ){
    $wp_rewrite->rules = array_merge(
        ['converter/?$' => 'index.php?converter=1'],
        $wp_rewrite->rules
    );
} );
add_filter( 'query_vars', function( $query_vars ){
    $query_vars[] = 'converter';
    return $query_vars;
} );
add_action( 'template_redirect', function(){
    $converter = intval( get_query_var( 'converter' ) );
    if ( $converter ) {
        include plugin_dir_path( __FILE__ ) . 'templates/converter.php';
        die;
    }
} );

function BanglaConverter_activate() { 
    // Clear the permalinks after the post type has been registered.
    flush_rewrite_rules(); 
}
register_activation_hook( __FILE__, 'BanglaConverter_activate' );

/**
 * Proper way to enqueue scripts and styles
 */
function BanglaConverterCssJs() {
    wp_enqueue_style( 'converter-css', plugins_url('css/converter.css',__FILE__ ) );

}
add_action( 'wp_enqueue_scripts', 'BanglaConverterCssJs' );


add_action( 'wp_ajax_bnconverter_action', 'bnconverter_action' );

function bnconverter_action() {
    if ($_POST['convert'] == "u2b") {
        echo esc_html(convertUnicodeToBijoy($_POST['text']));
    }elseif($_POST['convert'] == "b2u"){
      echo esc_html(convertBijoyToUnicode($_POST['text']));
    }
   

         

    wp_die(); // this is required to terminate immediately and return a proper response
}

/**
 * Generated by the WordPress Option Page generator
 * at http://jeremyhixon.com/wp-tools/option-page/
 */

class BanglaConverter {
    private $bangla_converter_options;

    public function __construct() {
        add_action( 'admin_menu', array( $this, 'bangla_converter_add_plugin_page' ) );
        add_action( 'admin_init', array( $this, 'bangla_converter_page_init' ) );
    }

    public function bangla_converter_add_plugin_page() {
        add_menu_page(
            'Bangla Converter', // page_title
            'Bangla Converter', // menu_title
            'manage_options', // capability
            'bangla-converter', // menu_slug
            array( $this, 'bangla_converter_create_admin_page' ), // function
            'dashicons-admin-generic', // icon_url
            80 // position
        );
    }

    public function bangla_converter_create_admin_page() {
        $this->bangla_converter_options = get_option( 'bangla_converter_option_name' ); ?>

        <div class="wrap">
            <h2>Bangla Converter</h2>
            <p></p>
            <?php settings_errors(); ?>

            <form method="post" action="options.php">
                <?php
                    settings_fields( 'bangla_converter_option_group' );
                    do_settings_sections( 'bangla-converter-admin' );
                    submit_button();
                ?>
                <p style="font-size:18px">Converter Link: <a href="<?php echo get_site_url().'/converter'; ?>" target="_blank"><?php echo get_site_url().'/converter'; ?></a></p>
            </form>
        </div>
    <?php }

    public function bangla_converter_page_init() {
        register_setting(
            'bangla_converter_option_group', // option_group
            'bangla_converter_option_name', // option_name
            array( $this, 'bangla_converter_sanitize' ) // sanitize_callback
        );

        add_settings_section(
            'bangla_converter_setting_section', // id
            'Settings', // title
            array( $this, 'bangla_converter_section_info' ), // callback
            'bangla-converter-admin' // page
        );

        add_settings_field(
            'logo_url_0', // id
            'Logo Url', // title
            array( $this, 'logo_url_0_callback' ), // callback
            'bangla-converter-admin', // page
            'bangla_converter_setting_section' // section
        );

        add_settings_field(
            'copyright_text_1', // id
            'Copyright Text', // title
            array( $this, 'copyright_text_1_callback' ), // callback
            'bangla-converter-admin', // page
            'bangla_converter_setting_section' // section
        );
    }

    public function bangla_converter_sanitize($input) {
        $sanitary_values = array();
        if ( isset( $input['logo_url_0'] ) ) {
            $sanitary_values['logo_url_0'] = sanitize_text_field( $input['logo_url_0'] );
        }

        if ( isset( $input['copyright_text_1'] ) ) {
            $sanitary_values['copyright_text_1'] = sanitize_text_field( $input['copyright_text_1'] );
        }

        return $sanitary_values;
    }

    public function bangla_converter_section_info() {
        
    }

    public function logo_url_0_callback() {
        printf(
            '<input class="regular-text" type="text" name="bangla_converter_option_name[logo_url_0]" id="logo_url_0" value="%s">',
            isset( $this->bangla_converter_options['logo_url_0'] ) ? esc_attr( $this->bangla_converter_options['logo_url_0']) : ''
        );
    }

    public function copyright_text_1_callback() {
        printf(
            '<input class="regular-text" type="text" name="bangla_converter_option_name[copyright_text_1]" id="copyright_text_1" value="%s">',
            isset( $this->bangla_converter_options['copyright_text_1'] ) ? esc_attr( $this->bangla_converter_options['copyright_text_1']) : ''
        );
    }

}
if ( is_admin() )
    $bangla_converter = new BanglaConverter();

/* 
 * Retrieve this value with:
 * $bangla_converter_options = get_option( 'bangla_converter_option_name' ); // Array of All Options
 * $logo_url_0 = $bangla_converter_options['logo_url_0']; // Logo Url
 * $copyright_text_1 = $bangla_converter_options['copyright_text_1']; // Copyright Text
 */
